apiVersion: v1
kind: Pod
metadata:
  name : tiger
spec:
  containers:
    - name : mylove
      image: nginx
      volumeMounts:
        - name: voldirr
          mountPath: /test-mnts
  volumes:
    - name: voldirr
      persistentVolumeClaim:
        claimName: mypvcd
