apiVersion: v1
kind: Pod
metadata:
  name : sai
spec:
  containers:
    - name : myjob
      image: nginx
      volumeMounts:
        - name: test-pro
          mountPath: /test-pds
  volumes:
    - name: test-pro
      gcePersistentDisk:
        pdName: swe
        fsType: ext4
