apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk: 
    pdName: swe
    fsType: ext4

