apiVersion: v1
kind: Pod
metadata:
  name : dog
spec:
  containers:
    - name : myc
      image: nginx
      volumeMounts:
        - name: voldir
          mountPath: /test-pds
  volumes:
    - name: voldir
      persistentVolumeClaim:
        claimName: mypvc
