apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate :
      maxUnavailable : 0
      maxSurge : 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ngin
          image: nginx
          ports:
            - containerPort : 80
        readinessProbe :
          httpdGet :
            port : 80
          intialDelaySeconds : 5
          periodSeconds : 5

