apiVersion: v1
kind: Pod
metadata:
  name : love
spec:
 containers:
   - name : mycon
     image: nginx
     env:
       - name: xxx
         valueFrom:
           configMapKeyRef:
             name: siacm
             key: filex
       - name: yyy
         valueFrom:
           configMapKeyRef:
             name: siacm
             key: filey
 restartPolicy: Never           




