apiVersion: v1
kind: Pod
metadata:
  name : love
spec:
 containers:
   - name : mycon
     image: nginx
     volumeMounts:
     - name: test-vol
       mountPath: /gopi/xuv
       readOnly: true
 volumes:
   - name: test-vol
     secret:
       secretName: myse 
