apiVersion: v1
kind: Pod
metadata:
  name: lia
spec:
  containers:
    - name: mycon
      image: nginx
      env: 
        - name: tree
          valueFrom:
            secretKeyRef:
              name: its
              key: usrname
        - name: fruit
          valueFrom:
            secretKeyRef:
              name: its
              key: passwd

